### ISSUE TITLE
No such file or directory: 'stockfish'

### ISSUE THREAD

**Issue by cemox** [staubsauger/ChessnutPy#1]
Hello, this looks like an amazing project, thank you.

[Ubuntu 22.04]
When I ran the main.py, it connects to my chessnut air without any issues, but it gives the error "no such file directory: stockfish". 

I actually build stockfish 16 from source and it works in terminal (I tested it).  I put the stockfish executable file in the same directory as main.py.  Can you help?

**Comment by cemox** [comment]
Solved it, by changing  `engine_cmd = "stockfish"` to `engine_cmd = "./stockfish" in the config file. 
`

**Comment by staubsauger** [comment]
Yeah, it's in the description. You should copy the config file to your homedir. There you can config the engines. As you maybe already know, you can also use other engines. In the config there should be a path for the engine, you want to play against and there is also a path for the analysis engine. Let me know how you like the program and also, if you find any bugs.

**Comment by cemox** [comment]
> Yeah, it's in the description. You should copy the config file to your homedir. There you can config the engines. As you maybe already know, you can also use other engines. In the config there should be a path for the engine, you want to play against and there is also a path for the analysis engine. Let me know how you like the program and also, if you find any bugs.

Wonderful project, thank you. I am working on your code, I will let you know if I find any bugs. 

One thing I noticed though, when I disabled server by setting `no-server = true`, an exception occurs right after it is connected to the board: "RuntimeError: no current event loop in thread 'MainThread'

**Comment by staubsauger** [comment]
Thanks. I made a new issue for this problem. Thanks for your help!
