### ISSUE TITLE
just a few general remarks

### ISSUE THREAD

**Issue by TomMuc1** [staubsauger/ChessnutPy#11]
first of all - great how you're getting on with it and making progress!

1) image: i think it would be better to use only the raspbian bullseye 32bit without desktop. the kioskmode with chromium is already a resource-hungry (especially if hardware acceleration isn't deactivated in chromium) nonsense with picochess. running the gui via a webserver (preferably nginx) is more modern and resource-saving. in addition, the created user should be called 'pi' according to the raspberry-pi conventions and not 'chess'.

2) the first important thing now would be to polish up the graphical interface and bring it to a professional level and make the application error-free and robust. only then should new features and engines be added. nothing is more important than the user interface and reliability. it's just like a car.

3) in the app itself, some paths don't seem to be really well done because it doesn't work as a service with systemctl without further ado - even if you call main.py in the service via the bash, for example: ExecStart=/bin/bash -c 'cd /home/chess/chessnutpy/ && python3 main.py'.

cheers
tom

**Comment by staubsauger** [comment]
Check out our new release. It is not bullseye, as we said. But it is a 32 bit image which should boot within 30 secs. Greets, Rudi and Lukas

**Comment by TomMuc1** [comment]
ja. gratulation. bei mir bootet das raspian 32 bit lite bis chessnutpy und bluetooth-connect zum chessnut air in 25 sekunden sogar auf nem pi zero 2. davon ab is bei so ner app die bootzeit so ziemlich das uninteressanteste ueberhaupt. ob 15 oder 60 sekunden - who cares ...

und ohne boes sein zu wollen - euer neues webinterface und menue is ne user-interface-katastrophe.

cheers
tom

p.s. schaus mir aber morgen mal an euer machwerk :)

**Comment by TomMuc1** [comment]
hab neues image ausprobiert. verbindet sich mit board - kein wifi trotz wpa_supplicant.conf. geht nur wenn man ueber lan zugreift und dann wifi manuell anlegt.
