### ISSUE TITLE
same error on MacOS 14.0 and Raspbian GNU/Linux 11 (bullseye)

### ISSUE THREAD

**Issue by TomMuc1** [staubsauger/ChessnutPy#5]
Traceback (most recent call last):
  File "/home/pi/ChessnutPy-main/./main.py", line 8, in <module>
    from BoardGame import BoardGame
  File "/home/pi/ChessnutPy-main/BoardGame.py", line 10, in <module>
    from ChessnutAir import ChessnutAir, board_state_as_square_and_piece
  File "/home/pi/ChessnutPy-main/ChessnutAir.py", line 42, in <module>
    class ChessnutAir:
  File "/home/pi/ChessnutPy-main/ChessnutAir.py", line 125, in ChessnutAir
    async def change_leds(self, list_of_pos: list[str] | chess.SquareSet) -> None:
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'type'

**Comment by staubsauger** [comment]
Could you provide the output of "python --version"? We tested with python 3.10 and 3.11.

**Comment by staubsauger** [comment]
try pulling the repo again. Maybe I found a quick fix.

**Comment by TomMuc1** [comment]
did a fresh download - but again on mac and raspi. sorry to bother ...

MacOS 14.0 - Python 3.9.6 =>
/Users/userworktr/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/userworktr/Desktop/ChessnutPy-main/main.py", line 8, in <module>
    from BoardGame import BoardGame
  File "/Users/userworktr/Desktop/ChessnutPy-main/BoardGame.py", line 10, in <module>
    from ChessnutAir import ChessnutAir, board_state_as_square_and_piece
  File "/Users/userworktr/Desktop/ChessnutPy-main/ChessnutAir.py", line 42, in <module>
    class ChessnutAir:
  File "/Users/userworktr/Desktop/ChessnutPy-main/ChessnutAir.py", line 150, in ChessnutAir
    async def play_animation(self, list_of_frames: list[list[str] | chess.SquareSet], sleep_time: float = 0.5) -> None:
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'type'


Raspbian GNU/Linux 11 (bullseye) - Python 3.9.2 =>
Traceback (most recent call last):
  File "/home/pi/ChessnutPy-main/./main.py", line 8, in <module>
    from BoardGame import BoardGame
  File "/home/pi/ChessnutPy-main/BoardGame.py", line 10, in <module>
    from ChessnutAir import ChessnutAir, board_state_as_square_and_piece
  File "/home/pi/ChessnutPy-main/ChessnutAir.py", line 42, in <module>
    class ChessnutAir:
  File "/home/pi/ChessnutPy-main/ChessnutAir.py", line 150, in ChessnutAir
    async def play_animation(self, list_of_frames: list[list[str] | chess.SquareSet], sleep_time: float = 0.5) -> None:
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'type'

**Comment by staubsauger** [comment]
Try "git pull". Should be fixed already.

**Comment by TomMuc1** [comment]
now the errors on both machines are differnt than before:

MacOS 14.0 - Python 3.9.6 =>
/Users/userworktr/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Namespace(no_server=False, hosts='auto-hosts', port=8080, engine_cmd='stockfish', engine_cfg={}, engine_time=0.5, engine_depth=None, engine_nodes=None, sug_time=5, sug_depth=None, sug_nodes=None, no_suggestions=False, engine_suggest_cmd='stockfish', suggestion_book_dir='./Docs/Elo2400.bin', eco_file='./Docs/scid.eco', lichess_token='', experimental_dragging_detection=False, experimental_dragging_timeout=0.3, show_valid_moves=True, play_animations=True, show_would_have_done_move=True)
192.168.144.2
unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-1' coro=<_run_app() done, defined at /Users/userworktr/Library/Python/3.9/lib/python/site-packages/aiohttp/web.py:289> exception=ValueError('malformed node or string: {}')>
Traceback (most recent call last):
  File "/Users/userworktr/Library/Python/3.9/lib/python/site-packages/aiohttp/web.py", line 516, in run_app
    loop.run_until_complete(main_task)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/userworktr/Library/Python/3.9/lib/python/site-packages/aiohttp/web.py", line 310, in _run_app
    app = await app  # type: ignore[misc]
  File "/Users/userworktr/Desktop/ChessnutPy-main/main.py", line 27, in go
    engine_cfg=ast.literal_eval(options.engine_cfg),
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ast.py", line 105, in literal_eval
    return _convert(node_or_string)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ast.py", line 104, in _convert
    return _convert_signed_num(node)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ast.py", line 78, in _convert_signed_num
    return _convert_num(node)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ast.py", line 69, in _convert_num
    _raise_malformed_node(node)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ast.py", line 66, in _raise_malformed_node
    raise ValueError(f'malformed node or string: {node!r}')
ValueError: malformed node or string: {}
Traceback (most recent call last):
  File "/Users/userworktr/Desktop/ChessnutPy-main/main.py", line 96, in <module>
    web.run_app(go(), host=hosts, port=8080)
  File "/Users/userworktr/Library/Python/3.9/lib/python/site-packages/aiohttp/web.py", line 516, in run_app
    loop.run_until_complete(main_task)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/userworktr/Library/Python/3.9/lib/python/site-packages/aiohttp/web.py", line 310, in _run_app
    app = await app  # type: ignore[misc]
  File "/Users/userworktr/Desktop/ChessnutPy-main/main.py", line 27, in go
    engine_cfg=ast.literal_eval(options.engine_cfg),
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ast.py", line 105, in literal_eval
    return _convert(node_or_string)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ast.py", line 104, in _convert
    return _convert_signed_num(node)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ast.py", line 78, in _convert_signed_num
    return _convert_num(node)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ast.py", line 69, in _convert_num
    _raise_malformed_node(node)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ast.py", line 66, in _raise_malformed_node
    raise ValueError(f'malformed node or string: {node!r}')
ValueError: malformed node or string: {}



Raspbian GNU/Linux 11 (bullseye) - Python 3.9.2 =>
Traceback (most recent call last):
  File "/home/pi/.local/share/Trash/files/ChessnutPy-main.2/./main.py", line 8, in <module>
    from BoardGame import BoardGame
  File "/home/pi/.local/share/Trash/files/ChessnutPy-main.2/BoardGame.py", line 10, in <module>
    from ChessnutAir import ChessnutAir, board_state_as_square_and_piece
  File "/home/pi/.local/share/Trash/files/ChessnutPy-main.2/ChessnutAir.py", line 42, in <module>
    class ChessnutAir:
  File "/home/pi/.local/share/Trash/files/ChessnutPy-main.2/ChessnutAir.py", line 150, in ChessnutAir
    async def play_animation(self, list_of_frames: list[list[str] | chess.SquareSet], sleep_time: float = 0.5) -> None:
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'type'

**Comment by staubsauger** [comment]
Not so sure about the mac os problem. But on the pi, I'm sure you are not on the last version. Try "git pull" or redownload the repo on the pi.

**Comment by TomMuc1** [comment]
no unfortunately not. had on both computers again the complete zip archive downloaded and unpacked and before the old deleted. and now again individually the two python files changed by you in the last hour downloaded and replaced the existing. the error messages remain the same as in the last post

**Comment by staubsauger** [comment]
No need to change any files. Just delete the old repo and download it again. When you still get this on the pi: 

File "/home/pi/.local/share/Trash/files/ChessnutPy-main.2/ChessnutAir.py", line 150, in ChessnutAir
async def play_animation(self, list_of_frames: list[list[str] | chess.SquareSet], sleep_time: float = 0.5) -> None:
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'type'

you are not on the new version, as the line: 
async def play_animation(self, list_of_frames: list[list[str] | chess.SquareSet], sleep_time: float = 0.5) -> None

changed to:

async def play_animation(self, list_of_frames: list["list[str] | chess.SquareSet"], sleep_time: float = 0.5) -> None

**Comment by BierLiebHaber** [comment]
The MacOS error seems to be related to the configuration of the engine. Did you change anything in the configfile (especially the 'engine_cfg' part)?

**Comment by TomMuc1** [comment]
> The MacOS error seems to be related to the configuration of the engine. Did you change anything in the configfile (especially the 'engine_cfg' part)?

nope. did not change anything within the scripts.

**Comment by TomMuc1** [comment]
> No need to change any files. Just delete the old repo and download it again. When you still get this on the pi:
> 
> File "/home/pi/.local/share/Trash/files/ChessnutPy-main.2/ChessnutAir.py", line 150, in ChessnutAir async def play_animation(self, list_of_frames: list[list[str] | chess.SquareSet], sleep_time: float = 0.5) -> None: TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'type'
> 
> you are not on the new version, as the line: async def play_animation(self, list_of_frames: list[list[str] | chess.SquareSet], sleep_time: float = 0.5) -> None
> 
> changed to:
> 
> async def play_animation(self, list_of_frames: list["list[str] | chess.SquareSet"], sleep_time: float = 0.5) -> None

restarted the pi - and obviously the python must have cashed something?

anyways - now it's a step further:
pi@RaspPi4TR:~ $ cd ChessnutPy-main/
pi@RaspPi4TR:~/ChessnutPy-main $ python3 ./main.py
Namespace(no_server=False, hosts='auto-hosts', port=8080, engine_cmd='stockfish', engine_cfg="{'UCI_LimitStrength': True, 'UCI_Elo': 1400}", engine_time='0.5', engine_depth='None', engine_nodes='None', sug_time='5.0', sug_depth='None', sug_nodes='None', no_suggestions=False, engine_suggest_cmd='stockfish', suggestion_book_dir='./Docs/Elo2400.bin', eco_file='./Docs/scid.eco', lichess_token='', experimental_dragging_detection=False, experimental_dragging_timeout=0.3, show_valid_moves=True, play_animations=True, show_would_have_done_move=True)
192.168.143.12
read eco_dict
scanning, please wait...
done scanning
device.address:  XX:XX:XX:XX:XX:XX
======== Running on http://192.168.143.12:8080, http://localhost:8080 ========
(Press CTRL+C to quit)
Connected: True
Initialized
piece: r at h8 down
piece: n at g8 down
piece: b at f8 down
piece: k at e8 down
piece: q at d8 down
piece: b at c8 down
piece: n at b8 down
piece: r at a8 down
piece: p at h7 down
piece: p at g7 down
piece: p at f7 down
piece: p at e7 down
piece: p at d7 down
piece: p at c7 down
piece: p at b7 down
piece: p at a7 down
piece: P at h2 down
piece: P at g2 down
piece: P at f2 down
piece: P at e2 down
piece: P at d2 down
piece: P at c2 down
piece: P at b2 down
piece: P at a2 down
piece: R at h1 down
piece: N at g1 down
piece: B at f1 down
piece: K at e1 down
piece: Q at d1 down
piece: B at c1 down
piece: N at b1 down
piece: R at a1 down
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<ChessnutAir.run() done, defined at /home/pi/ChessnutPy-main/ChessnutAir.py:215> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/home/pi/ChessnutPy-main/ChessnutAir.py", line 237, in run
    await self.game_loop()  # call user game loop
  File "/home/pi/ChessnutPy-main/BoardGame.py", line 467, in game_loop
    await self.game.init_engines()
  File "/home/pi/ChessnutPy-main/EngineManager.py", line 48, in init_engines
    self.transport, self.engine = await chess.engine.popen_uci(self.engine_path)
  File "/home/pi/.local/lib/python3.9/site-packages/chess/engine.py", line 2679, in popen_uci
    transport, protocol = await UciProtocol.popen(command, setpgrp=setpgrp, **popen_args)
  File "/home/pi/.local/lib/python3.9/site-packages/chess/engine.py", line 1239, in popen
    return await asyncio.get_running_loop().subprocess_exec(cls, *command, **popen_args)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1661, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.9/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/lib/python3.9/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/lib/python3.9/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'stockfish'

**Comment by staubsauger** [comment]
You are missing stockfish. Try "sudo apt install stockfish".

**Comment by TomMuc1** [comment]
ok. now it finds the board and sees when the white king is lifted and placed back. but after pawwn e2e4 ...

Button 1 pressed!
New Game without PGN save
Board settled
board correct:
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R
select a color by picking up a king
piece: e1 at K up
piece: K at e1 down
Selected White
board correct:
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R
piece: e2 at P up
piece: P at e4 down
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . P . . .
. . . . . . . .
P P P P . P P P
R N B Q K B N R
Move-stack:  ['e2e4']
Player move:  e2e4
[('B00a', "King's Pawn")]
Entry(key=5060803636482931868, raw_move=731, weight=14247, learn=0, move=Move.from_uci('d2d4'))
generated Move: g8f6
board incorrect!
please fix

**Comment by staubsauger** [comment]
So no LEDs light up? Turn the board on and off and restart the program.

**Comment by TomMuc1** [comment]
but hey - i'm from munich - maybe before writing the next two million lines here on github a short phone-call is the faster/easier solution if it's ok for you.

**Comment by staubsauger** [comment]
Eigentlich nicht notwendig. Du hast fasst geschafft.  "generated Move: g8f6 " ist halt der Zug, also ist das " board incorrect!". Also sollten eigentlich die beiden LEDs g8 und f6 leuchten. Wenn du dann den Springer auf das Feld stellst, sollte das "board fixed" sein und du bist wieder an der Reihe.

**Comment by TomMuc1** [comment]
ja klar. aber es zappeln dann auch immer mal wieder leds der weissen seite bevor man den zug fuer schwarz gemacht hat. und das boerd ist einwandfrei und funktioniert bei chess.com mit dem chrome chessconnect plugin wunderbar.

**Comment by TomMuc1** [comment]
und bei der rochade kommen dann auch eher sinnfreie meldungen und ledgeblinke. aber hey - zumindest groessenordnungsmaessig funktionierts ja schon mal.

**Comment by staubsauger** [comment]
ja, das kannst du aus stellen. Das ist der Move, der der Computer gemacht hätte. In der config "show_would_have_done_move=true" auf "show_would_have_done_move=false" setzen.

**Comment by staubsauger** [comment]
> und bei der rochade kommen dann auch eher sinnfreie meldungen und ledgeblinke. aber hey - zumindest groessenordnungsmaessig funktionierts ja schon mal.

Ja, ist noch nicht alles ganz fertig.

**Comment by TomMuc1** [comment]
auf jeden fall find ichs ganz cool was ihr zwei da waehrend biertrinken und staubsaugen macht ;) is der plan da jetzt auch a gui dranzubasteln oder soll das mit der shell so bleiben?

**Comment by staubsauger** [comment]
Unter "localhost:8080/" oder eben unter der IP des Rechners ist ein webinterface erreichbar. Da siehst du etwas mehr. Ein Gui ist nicht geplant. Das meiste geht ja über das Board und die Idee war, Schach gegen den Computer spielen zu können, ohne durch ein Display abgelenkt zu werden.

**Comment by TomMuc1** [comment]
ah - cool. ja funktioniert bei mir. und wunderbarerweise zeigts auch nach 8 zugpaaren genau das an was auf dem physischen brett zu sehen ist :)

mit gui meinte ich auch a browser-interface.

wenn da jetzt noch unterschiedliche engines installierbar waeren und deren settings ueber das webinterface funktionierten und das sowohl auf handy/tablet/pc vernuenftig dargestellt waers der knaller.

und fuer sowas das ohne rumgefrickel funktioniert und am besten als fertiges image fuer nen pi vorliegt wuerd ich sofort immer 30-50 euro ausgeben.

**Comment by staubsauger** [comment]
Ich werde voraussichtlich im Laufe der Woche ein Image bereitstellen. Ich bastel gerade eins, es ist aber noch nicht ganz fertig. Das Webinterface ist mehr eine brauchbare Bautstelle :) Aber darüber solltest du bereits ein paar Sachen einstellen können. Aber ich weiß nicht wie gut das bisher funktioniert.

**Comment by BierLiebHaber** [comment]
andere engines müssten funktionieren wenn du den Befehl in der `./Docs/default.conf` unter engine_cmd einträgst
also statt `engine_cmd = "stockfish"`
z.B. (wenn texel systemweit installiert ist) `engine_cmd = "texel"`
oder `engine_cmd = "/pfad/zu/texel"` wenn es lokal installiert ist

**Comment by TomMuc1** [comment]
finde es wirklich ne super sache! und da das besser ist als alles was chessnut selber an software auf die beine stellt solltet ihr auch die mal fragen ob sie nicht mal 4-5 stelliges dankeschoen rueberwachsen lassen wollen.

andererseits koenntet ihr es ja auch auf eboards anderer hersteller ausweiten. und wenn das dann als image fuer nen pi vorliegt und man uebers webinterface angines installieren und einstellen kann und das board aussuchen. isses a software fuer die man fraglos 50 euro pro lizenz verlangen kann.

**Comment by staubsauger** [comment]
Jo dank dir. Das hören wir gerne. Aktuell haben wir nur ein Board und daher ist das Entwickeln manchmal etwas kompliziert. Wir überlegen, demnächst mal "den Hut" aufzustellen, um noch ein weiteres Board zu kaufen. Da würden wir uns über eine Spende freuen. MFG

**Comment by TomMuc1** [comment]
ich schreib den chinesen die tage mal a email als kundenfeedback dass ich ihr board entweder zurueckgeschickt oder in die tonne geworfen haette wenn es nicht des chessconnect-plugin fuer den chrome und jetzt euer projekt gaebe.

deren apps sind naemlich leider hirntoter schrott der schon 2010 als alter mist gegolten haette.

vielleicht bringen die ja dann mal den hintern hoch und spenden euch und dem anderen mal ein board und nicht immer nur irgendwelchen youtube heinis die null mehrwert nur gequatsche produzieren ...

**Comment by TomMuc1** [comment]
> ja, das kannst du aus stellen. Das ist der Move, der der Computer gemacht hätte. In der config "show_would_have_done_move=true" auf "show_would_have_done_move=false" setzen.

hmmm. in docs/default.config isses bereits auf false. und in der main.py isses auf true als ausgabe. und mit kommentaren in eurem code seid ihr ja eher sparsam. wie und wo also?

**Comment by BierLiebHaber** [comment]
hm eigentlich ist das der Ort wo man es ändern kann. ausser es gibt eine `~/.config/chessnutair.config`, dann nimmt es die optionen daraus
kannst du mal die aktuelle version runterladen und dann nochmal den output vor
`======== Running on http://192.168.143.12:8080/, http://localhost:8080/ ========`
posten? (da müsste jetzt drin stehen woher die option kommt)

**Comment by TomMuc1** [comment]
yup - hier. aber wie schon vorher gesagt - manchmal leuchten wirr irgendwelche weissen felder auch wenn er mit schwarz selber am zug ist und man die figur fuer ihn noch ned gefuehrt hat. manchmal laesst er ohne sinn meine zuege nicht zu und ein anderer zug geht problemlos. und im endspiel isser dann irgendwann laengst vor matt tot und ruehrt sich nimmer. ich habs in 4 versuchen nicht einmal geschafft dass er mich matt setzt.

cheers


Config File (./Docs/default.config):
  engine_cmd:        stockfish
  engine_cfg:        {'UCI_LimitStrength': True, 'UCI_Elo': 1400}
  suggestion_book_dir:./Docs/Elo2400.bin
  engine_time:       0.5
  engine_depth:      None
  engine_nodes:      None
  no_suggestions:    false
  engine_suggest_cmd:stockfish
  eco_file:          ./Docs/scid.eco
  sug_time:          5.0
  sug_depth:         None
  sug_nodes:         None
  show_would_have_done_move:false
  experimental_dragging_detection:false
  experimental_dragging_timeout:0.3
  play_animations:   true
  show_valid_moves:  false
  no_server:         false
  hosts:             auto-hosts
  port:              8080
  lichess_token:
192.168.143.12
20819
duplicates: 1
wrote eco_dict
scanning, please wait...
done scanning
device.address:

**Comment by TomMuc1** [comment]
aber wie gesagt - geb euch gern mal a kurzes feedback am tel statt hier nen roman hin und her zu schreiben ...

**Comment by BierLiebHaber** [comment]
Jetzt müsste `show_would_have_done_move` auf false sein, also sollte es hoffentlich weniger blinken.
Wenn du deine Figuren schiebst beim ziehen (also nicht auf- und absetzt) dann musst du `experimental_dragging_detection=true` in die config schreiben, sonst erkennt er das Schieben nicht richtig.
ist aber leider noch nicht ganz ausgereift.
Das es zum ende hin abschmiert ist uns noch nicht passiert. Telefon ist leider nur so halb praktisch weil man zum debuggen am besten den output und das brett sieht. Falls du discord oder ähnliches (am besten mit webcam) hast könnte man es aber die Tage mal da probieren.

**Comment by TomMuc1** [comment]
also jungs - dann hab ich mal mit 10 euro den anfang gemacht ;)
mfg
tom

**Comment by staubsauger** [comment]
Hi, vielen Dank. Das ist sehr nett von dir und wird uns helfen. Wir sind aktuell wieder fleißig und werden die Tage das Image updaten. Herzliche Grüße

**Comment by TomMuc1** [comment]
gerne! btw - hab auch mal euer aktuelles image ausprobiert - hat aber bei mir nicht gebootet (pi 0/2/3). und es waere auch gut ihr wuerdet dazuschreiben welches raspbian genau (zb raspberry pi os (bullseye) with desktop) da als basis verwendet wird.

**Comment by staubsauger** [comment]
Hmm, also dass es auf dem Zero und den 2 nicht bootet ist normal. Ist ein 64 Bit Image. Auf dem 3er sollte es aber eigentlich gehen. Ich benutze immer usbimager unter Linux. Ansonsten sollte aber auch klassisch DD gehen. `sudo dd if=/pfad/von/image.img of=/pfad/zur/sdcard`
Ansonsten gibt es noch balena etcher. Das wird häufig unter Windows empfohlen.

**Comment by TomMuc1** [comment]
schon klar womit man das image dann schreiben kann.. bullseye oder bookworm? und wozu 64bit?

**Comment by staubsauger** [comment]
Die Basis ist voidlinux. Und warum 64 Bit, keine Ahnung :). Wenn ich es schaffe, bastel ich dir noch ein 32 Bit Image.

**Comment by TomMuc1** [comment]
super idee. die haben sicher 0,1% marktanteil auf den raspberry pi ...

**Comment by TomMuc1** [comment]
> Die Basis ist voidlinux. Und warum 64 Bit, keine Ahnung :). Wenn ich es schaffe, bastel ich dir noch ein 32 Bit Image.

das ist nett aber braucht es nicht. mein tipp waer halt nur gaengiges nutzen - und das is aktuell auf raspi halt 32bit bullseye mit desktop (ca 0,9gb das image). und halt auch in der hauptbranch und den releases nur zeug hochstellen das funktioniert. sonst probieren es alle - sind genervt weil nix geht - und kommen nie wieder.

**Comment by TomMuc1** [comment]
und btw - hier mal ein (absichtliches wirres) spiel wo es dann wieder nen brain-freeze gibt und man kann mit allen figuren weiterspielen nur mit dem weissen turm nicht. da nimmt er keinen zug mehr egal in welcher richtung
![screen](https://github.com/staubsauger/ChessnutPy/assets/31601862/91e1348b-b2a9-46a7-945d-55c5c023a4e0)

**Comment by staubsauger** [comment]
Ist doch unerheblich was die Basis ist. Hauptsache bootet schnell. Aber ich werde vielleicht noch ein 32 Bit Image machen. Ich schau mal wie viel langsamer Raspian ist. Vielleicht stellen wir auch um. Aber eigentlich ist voidlinux für dieses Projekt perfekt. 
Ich habe das Image auf einem Pi Zero 2, einem Pi4 und einem Pi 400 getestet. Da funktioniert es ganz gut, zumindest gab es nie den Fehler, dass es gar nicht bootet.

**Comment by staubsauger** [comment]
> und btw - hier mal ein (absichtliches wirres) spiel wo es dann wieder nen brain-freeze gibt und man kann mit allen figuren weiterspielen nur mit dem weissen turm nicht. da nimmt er keinen zug mehr egal in welcher richtung

Das Bild konnte ich nur kurz sehen, dann war es weg. Hast du es wieder gelöscht?

**Comment by TomMuc1** [comment]
> Ist doch unerheblich was die Basis ist. Hauptsache bootet schnell. Aber ich werde vielleicht noch ein 32 Bit Image machen. Ich schau mal wie viel langsamer Raspian ist. Vielleicht stellen wir auch um. Aber eigentlich ist voidlinux für dieses Projekt perfekt. Ich habe das Image auf einem Pi Zero 2, einem Pi4 und einem Pi 400 getestet. Da funktioniert es ganz gut, zumindest gab es nie den Fehler, dass es gar nicht bootet.

nope - is nicht 'unerheblich'. weils einfach banane ist ohne echten sehr grossen vorteil was anderes zu nehmen als das womit die meisten erfahrung haben und was sie nutzen. und wenn man was vor allem fuer den pi schreibt nimmt man raspbian - und da halt immer das meistgenutzte.

**Comment by staubsauger** [comment]
'Eigentlich' sollte das Image soweit vorkonfiguriert sein. Nach dem flashen die fat32 Partition öffenen, Wlan eistellen, SD in den Pi packen, booten, Brett anschalten und warten bis es verbindet. Aber Lukas und ich werden das mal bequatschen.

**Comment by staubsauger** [comment]
> und btw - hier mal ein (absichtliches wirres) spiel wo es dann wieder nen brain-freeze gibt und man kann mit allen figuren weiterspielen nur mit dem weissen turm nicht. da nimmt er keinen zug mehr egal in welcher richtung ![screen](https://user-images.githubusercontent.com/31601862/278619877-91e1348b-b2a9-46a7-945d-55c5c023a4e0.jpg)

Das ist ein wirklich komischer Fehler. Ich glaube allerdings nicht dass das etwas mit unserem Kram zu tun hat. Aber wir gucken da auf jeden Fall mal rein.

**Comment by TomMuc1** [comment]
> > und btw - hier mal ein (absichtliches wirres) spiel wo es dann wieder nen brain-freeze gibt und man kann mit allen figuren weiterspielen nur mit dem weissen turm nicht. da nimmt er keinen zug mehr egal in welcher richtung ![screen](https://user-images.githubusercontent.com/31601862/278619877-91e1348b-b2a9-46a7-945d-55c5c023a4e0.jpg)
> 
> Das ist ein wirklich komischer Fehler. Ich glaube allerdings nicht dass das etwas mit unserem Kram zu tun hat. Aber wir gucken da auf jeden Fall mal rein.

hab ich nur mit eurem chessnutpy. mit dem chessnut-air bei picochess chess.com chessnut-app etc - null probleme.

**Comment by TomMuc1** [comment]
does boot on zero 2 - but no login with pi/chess ???
